-- =====================================================
-- ONLINE VOTING SYSTEM - COMPLETE DATABASE SCHEMA
-- =====================================================
-- Consolidated schema with all tables, sequences, triggers,
-- and fixes in one file
-- Version: 1.0.0
-- =====================================================

-- Drop existing tables if needed (uncomment to use)
-- DROP TABLE VOTING_VOTES;
-- DROP TABLE VOTING_VOTE_SESSIONS;
-- DROP TABLE VOTING_CANDIDATES;
-- DROP TABLE VOTING_PARTIES;
-- DROP TABLE VOTING_CONSTITUENCIES;
-- DROP TABLE VOTING_OTP_VERIFICATION;
-- DROP TABLE VOTING_USERS;

-- =====================================================
-- 1. VOTING_USERS TABLE
-- =====================================================
CREATE TABLE VOTING_USERS (
    ID NUMBER(19) PRIMARY KEY,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    IS_VERIFIED NUMBER(1) DEFAULT 0 CHECK (IS_VERIFIED IN (0,1)),
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    FAILED_LOGIN_ATTEMPTS NUMBER(2) DEFAULT 0,
    ACCOUNT_LOCKED_UNTIL TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create sequence for VOTING_USERS table
CREATE SEQUENCE SEQ_VOTING_USERS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create trigger for auto-incrementing ID
CREATE OR REPLACE TRIGGER TRG_VOTING_USERS_ID
    BEFORE INSERT ON VOTING_USERS
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_VOTING_USERS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Create trigger for updating UPDATED_AT
CREATE OR REPLACE TRIGGER TRG_VOTING_USERS_UPDATED_AT
    BEFORE UPDATE ON VOTING_USERS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- =====================================================
-- 2. VOTING_OTP_VERIFICATION TABLE
-- =====================================================
CREATE TABLE VOTING_OTP_VERIFICATION (
    ID NUMBER(19) PRIMARY KEY,
    EMAIL VARCHAR2(255) NOT NULL,
    OTP_CODE VARCHAR2(6) NOT NULL,
    PURPOSE VARCHAR2(50) NOT NULL, -- 'REGISTRATION', 'VOTING', 'PASSWORD_RESET'
    EXPIRY_TIME TIMESTAMP NOT NULL,
    ATTEMPTS NUMBER(2) DEFAULT 0,
    IS_USED NUMBER(1) DEFAULT 0 CHECK (IS_USED IN (0,1)),
    USED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create sequence for VOTING_OTP_VERIFICATION table
CREATE SEQUENCE SEQ_VOTING_OTP_VERIFICATION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create trigger for auto-incrementing ID
CREATE OR REPLACE TRIGGER TRG_VOTING_OTP_VERIFICATION_ID
    BEFORE INSERT ON VOTING_OTP_VERIFICATION
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_VOTING_OTP_VERIFICATION.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- =====================================================
-- 3. VOTING_CONSTITUENCIES TABLE
-- =====================================================
CREATE TABLE VOTING_CONSTITUENCIES (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL UNIQUE,
    STATE VARCHAR2(100) NOT NULL,
    DISTRICT VARCHAR2(100),
    DESCRIPTION CLOB,
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create sequence for VOTING_CONSTITUENCIES table
CREATE SEQUENCE SEQ_VOTING_CONSTITUENCIES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create trigger for auto-incrementing ID
CREATE OR REPLACE TRIGGER TRG_VOTING_CONSTITUENCIES_ID
    BEFORE INSERT ON VOTING_CONSTITUENCIES
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_VOTING_CONSTITUENCIES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Create trigger for updating UPDATED_AT
CREATE OR REPLACE TRIGGER TRG_VOTING_CONSTITUENCIES_UPDATED_AT
    BEFORE UPDATE ON VOTING_CONSTITUENCIES
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- =====================================================
-- 4. VOTING_PARTIES TABLE
-- =====================================================
CREATE TABLE VOTING_PARTIES (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    SYMBOL VARCHAR2(100),
    DESCRIPTION CLOB,
    LOGO_URL VARCHAR2(500), -- Path to party logo image
    COLOR_CODE VARCHAR2(7), -- Hex color code for UI
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create sequence for VOTING_PARTIES table
CREATE SEQUENCE SEQ_VOTING_PARTIES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create trigger for auto-incrementing ID
CREATE OR REPLACE TRIGGER TRG_VOTING_PARTIES_ID
    BEFORE INSERT ON VOTING_PARTIES
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_VOTING_PARTIES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Create trigger for updating UPDATED_AT
CREATE OR REPLACE TRIGGER TRG_VOTING_PARTIES_UPDATED_AT
    BEFORE UPDATE ON VOTING_PARTIES
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- =====================================================
-- 5. VOTING_CANDIDATES TABLE
-- =====================================================
CREATE TABLE VOTING_CANDIDATES (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL,
    AGE NUMBER(3),
    QUALIFICATION VARCHAR2(500),
    BIO VARCHAR2(1000),
    PHOTO_URL VARCHAR2(255),
    PARTY_ID NUMBER(19) NOT NULL,
    CONSTITUENCY_ID NUMBER(19) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key constraints
    CONSTRAINT FK_VOTING_CANDIDATES_PARTY FOREIGN KEY (PARTY_ID) REFERENCES VOTING_PARTIES(ID),
    CONSTRAINT FK_VOTING_CANDIDATES_CONSTITUENCY FOREIGN KEY (CONSTITUENCY_ID) REFERENCES VOTING_CONSTITUENCIES(ID),
    
    -- Unique constraint: One candidate per party per constituency
    CONSTRAINT UQ_PARTY_CONSTITUENCY UNIQUE (PARTY_ID, CONSTITUENCY_ID)
);

-- Create sequence for VOTING_CANDIDATES table
CREATE SEQUENCE SEQ_VOTING_CANDIDATES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create trigger for auto-incrementing ID
CREATE OR REPLACE TRIGGER TRG_VOTING_CANDIDATES_ID
    BEFORE INSERT ON VOTING_CANDIDATES
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_VOTING_CANDIDATES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Create trigger for updating UPDATED_AT
CREATE OR REPLACE TRIGGER TRG_VOTING_CANDIDATES_UPDATED_AT
    BEFORE UPDATE ON VOTING_CANDIDATES
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- =====================================================
-- 6. VOTING_VOTES TABLE
-- =====================================================
CREATE TABLE VOTING_VOTES (
    ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    CONSTITUENCY_ID NUMBER(19) NOT NULL,
    CANDIDATE_ID NUMBER(19) NOT NULL,
    SESSION_ID VARCHAR2(255) NOT NULL, -- For tracking voting session
    STATUS VARCHAR2(50) DEFAULT 'CAST' NOT NULL, -- Vote status: CAST, PENDING, VERIFIED, FLAGGED, CANCELLED
    VOTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IP_ADDRESS VARCHAR2(45), -- IPv4 or IPv6
    USER_AGENT CLOB, -- Browser information
    
    -- Foreign key constraints
    CONSTRAINT FK_VOTING_VOTES_USER_ID FOREIGN KEY (USER_ID) REFERENCES VOTING_USERS(ID),
    CONSTRAINT FK_VOTING_VOTES_CONSTITUENCY_ID FOREIGN KEY (CONSTITUENCY_ID) REFERENCES VOTING_CONSTITUENCIES(ID),
    CONSTRAINT FK_VOTING_VOTES_CANDIDATE_ID FOREIGN KEY (CANDIDATE_ID) REFERENCES VOTING_CANDIDATES(ID),
    
    -- Unique constraint: One vote per user per constituency
    CONSTRAINT UQ_USER_CONSTITUENCY UNIQUE (USER_ID, CONSTITUENCY_ID)
);

-- Create sequence for VOTING_VOTES table
CREATE SEQUENCE SEQ_VOTING_VOTES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create trigger for auto-incrementing ID
CREATE OR REPLACE TRIGGER TRG_VOTING_VOTES_ID
    BEFORE INSERT ON VOTING_VOTES
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_VOTING_VOTES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- =====================================================
-- 7. VOTING_VOTE_SESSIONS TABLE
-- =====================================================
CREATE TABLE VOTING_VOTE_SESSIONS (
    ID NUMBER(19) PRIMARY KEY,
    SESSION_ID VARCHAR2(255) NOT NULL UNIQUE,
    USER_ID NUMBER(19) NOT NULL,
    OTP_VERIFIED NUMBER(1) DEFAULT 0 CHECK (OTP_VERIFIED IN (0,1)),
    STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT TIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP,
    IP_ADDRESS VARCHAR2(45),
    USER_AGENT CLOB,
    
    -- Foreign key constraints
    CONSTRAINT FK_VOTING_VOTE_SESSIONS_USER_ID FOREIGN KEY (USER_ID) REFERENCES VOTING_USERS(ID)
);

-- Create sequence for VOTING_VOTE_SESSIONS table
CREATE SEQUENCE SEQ_VOTING_VOTE_SESSIONS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create trigger for auto-incrementing ID
CREATE OR REPLACE TRIGGER TRG_VOTING_VOTE_SESSIONS_ID
    BEFORE INSERT ON VOTING_VOTE_SESSIONS
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_VOTING_VOTE_SESSIONS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

-- Users table indexes
CREATE INDEX IDX_VOTING_USERS_EMAIL ON VOTING_USERS(EMAIL);
CREATE INDEX IDX_VOTING_USERS_VERIFIED ON VOTING_USERS(IS_VERIFIED);
CREATE INDEX IDX_VOTING_USERS_ACTIVE ON VOTING_USERS(IS_ACTIVE);

-- OTP verification indexes
CREATE INDEX IDX_VOTING_OTP_EMAIL ON VOTING_OTP_VERIFICATION(EMAIL);
CREATE INDEX IDX_VOTING_OTP_EXPIRY ON VOTING_OTP_VERIFICATION(EXPIRY_TIME);
CREATE INDEX IDX_VOTING_OTP_PURPOSE ON VOTING_OTP_VERIFICATION(PURPOSE);

-- Constituencies table indexes
CREATE INDEX IDX_VOTING_CONSTITUENCIES_STATE ON VOTING_CONSTITUENCIES(STATE);
CREATE INDEX IDX_VOTING_CONSTITUENCIES_ACTIVE ON VOTING_CONSTITUENCIES(IS_ACTIVE);

-- Parties table indexes
CREATE INDEX IDX_VOTING_PARTIES_ACTIVE ON VOTING_PARTIES(IS_ACTIVE);

-- Votes table indexes
CREATE INDEX IDX_VOTING_VOTES_USER_ID ON VOTING_VOTES(USER_ID);
CREATE INDEX IDX_VOTING_VOTES_CONSTITUENCY_ID ON VOTING_VOTES(CONSTITUENCY_ID);
CREATE INDEX IDX_VOTING_VOTES_CANDIDATE_ID ON VOTING_VOTES(CANDIDATE_ID);
CREATE INDEX IDX_VOTING_VOTES_SESSION_ID ON VOTING_VOTES(SESSION_ID);
CREATE INDEX IDX_VOTING_VOTES_STATUS ON VOTING_VOTES(STATUS);
CREATE INDEX IDX_VOTING_VOTES_VOTED_AT ON VOTING_VOTES(VOTED_AT);

-- Vote sessions indexes
CREATE INDEX IDX_VOTING_VOTE_SESSIONS_SESSION_ID ON VOTING_VOTE_SESSIONS(SESSION_ID);
CREATE INDEX IDX_VOTING_VOTE_SESSIONS_USER_ID ON VOTING_VOTE_SESSIONS(USER_ID);
CREATE INDEX IDX_VOTING_VOTE_SESSIONS_EXPIRES_AT ON VOTING_VOTE_SESSIONS(EXPIRES_AT);

-- =====================================================
-- STORED PROCEDURES
-- =====================================================

-- Cleanup expired OTPs
CREATE OR REPLACE PROCEDURE CLEANUP_EXPIRED_OTPS AS
BEGIN
    DELETE FROM VOTING_OTP_VERIFICATION 
    WHERE EXPIRY_TIME < CURRENT_TIMESTAMP 
    AND IS_USED = 1;
    
    COMMIT;
END CLEANUP_EXPIRED_OTPS;
/

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================

COMMIT;

-- Check table creation
SELECT table_name FROM user_tables 
WHERE table_name LIKE 'VOTING_%'
ORDER BY table_name;

-- Check sequences
SELECT sequence_name FROM user_sequences 
WHERE sequence_name LIKE 'SEQ_%'
ORDER BY sequence_name;

-- Check indexes
SELECT index_name, table_name, uniqueness 
FROM user_indexes 
WHERE table_name IN ('VOTING_USERS', 'VOTING_OTP_VERIFICATION', 'VOTING_CONSTITUENCIES', 
                     'VOTING_PARTIES', 'VOTING_VOTES', 'VOTING_VOTE_SESSIONS')
ORDER BY table_name, index_name;
